SRCS += ../../M2M/QNICE/vhdl/tools.vhd
SRCS += ../vhdl/globals.vhd

SRCS += ../../M2M/vhdl/av_pipeline/video_modes_pkg.vhd
SRCS += ../../M2M/vhdl/uart.vhd
SRCS += ../../M2M/vhdl/av_pipeline/vga_controller.vhd
SRCS += ../../M2M/vhdl/tdp_ram.vhd
SRCS += ../../M2M/vhdl/2port2clk_ram.vhd
SRCS += ../../M2M/vhdl/vdrives.vhd

SRCS += ../vhdl/clk.vhd
SRCS += ../vhdl/life.vhd
SRCS += ../vhdl/video/shift_registers.vhd
SRCS += ../vhdl/controller/divmod.vhd
SRCS += ../vhdl/controller/bin2bcd.vhd
SRCS += ../vhdl/controller/count_ones.vhd
SRCS += ../vhdl/controller/statistics.vhd
SRCS += ../vhdl/controller/lfsr.vhd
SRCS += ../vhdl/controller/random.vhd
SRCS += ../vhdl/controller/keyboard.vhd
SRCS += ../vhdl/controller/controller.vhd
SRCS += ../vhdl/controller/drives.vhd
SRCS += ../vhdl/controller/controller_wrapper.vhd
SRCS += ../vhdl/video/font.vhd
SRCS += ../vhdl/video/vga_chars.vhd
SRCS += ../vhdl/video/video_text_mode.vhd
SRCS += ../vhdl/video/video_board.vhd
SRCS += ../vhdl/video/video_wrapper.vhd
SRCS += ../vhdl/mega65_core.vhd
SRCS += uart_dumper.vhd
SRCS += tb_statistics.vhd
SRCS += tb_life.vhd
SRCS += tb_mega65_core.vhd
SRCS += tb_bin2bcd.vhd

TB = life
TB = mega65_core
#TB = statistics
#TB = bin2bcd

GENERICS += -gG_CELL_BITS=4
GENERICS += -gG_ROWS=8
GENERICS += -gG_COLS=8
GENERICS += -gG_BOARD=R6

all:
	vlog glbl.v
	vcom -2008 $(SRCS)
	vsim -voptargs=+acc $(GENERICS) -do wave_$(TB).do tb_$(TB) glbl -c


